name: sunsetcoffee
favicon: null
layout_spectrum: 0.9532455448061228
typography_spectrum: 0.8223032809328288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2616930576041341
  lightness: 0.4650683186482638
  saturation: 0.05642983433790505
  rhythmicContrast: 0.50680095795542
purpose: []
